version = 0.1

[default]
[default.global.parameters]
stack_name = "kansa-backend"
region = "ap-northeast-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "kansa-backend"
no_fail_on_empty_changeset = true
parameter_overrides = """
StripeSubPrice1gb=price_1T1rgALIcAkrQUHDMNEj5JOi
StripeSubPrice5gb=price_1T1rg0LIcAkrQUHDStVvKQwH
StripeSubPrice10gb=price_1T1rg7LIcAkrQUHDnmpI4EDv
StripeCheckoutSuccessUrl=https://ph4k.aokigk.com
StripeCheckoutCancelUrl=https://ph4k.aokigk.com
CognitoCallbackUrl=https://ph4k.aokigk.com
CognitoLogoutUrl=https://ph4k.aokigk.com
FrontendAllowedOrigins=http://localhost:5173,http://127.0.0.1:5173,https://ph4k.aokigk.com
StripeAllowedReturnOrigins=http://localhost:5173,http://127.0.0.1:5173,https://ph4k.aokigk.com
DeveloperUserKeys=27843ac8-f001-7099-e676-c1478e6107df
"""

[dev]
[dev.global.parameters]
stack_name = "kansa-backend-dev"
region = "ap-northeast-1"

[dev.build.parameters]
cached = true
parallel = true

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "kansa-backend-dev"
no_fail_on_empty_changeset = true
parameter_overrides = """
StripeSubPrice1gb=price_1T1m0JQ3IwbMVZymVcmd4Fwj
StripeSubPrice5gb=price_1T1m4wQ3IwbMVZymVjLdxqeZ
StripeSubPrice10gb=price_1T1m6AQ3IwbMVZym7COtrcaE
DisableExecuteApiEndpoint=false
CognitoDomainPrefix=photohub4kansa-dev
StripeCheckoutSuccessUrl=https://dev.d3vej31wy18srw.amplifyapp.com
StripeCheckoutCancelUrl=https://dev.d3vej31wy18srw.amplifyapp.com
CognitoCallbackUrl=https://dev.d3vej31wy18srw.amplifyapp.com
CognitoLogoutUrl=https://dev.d3vej31wy18srw.amplifyapp.com
CognitoDevCallbackUrl=https://dev.d3vej31wy18srw.amplifyapp.com
CognitoDevLogoutUrl=https://dev.d3vej31wy18srw.amplifyapp.com
FrontendAllowedOrigins=http://localhost:5173,http://127.0.0.1:5173,https://dev.d3vej31wy18srw.amplifyapp.com
StripeAllowedReturnOrigins=http://localhost:5173,http://127.0.0.1:5173,https://dev.d3vej31wy18srw.amplifyapp.com
DeveloperUserKeys=27843ac8-f001-7099-e676-c1478e6107df
"""